version: '2.1'
services:
  nodeodm:
    image: opendronemap/nodeodm
    ports:
      - "3000"
    restart: on-failure:10
    deploy:
      replicas: ${NODEODM_REPLICAS:-3}
      resources:
        limits:
          cpus: "2"
          memory: 2000M
        reservations:
          cpus: "0.1"
          memory: 100M
  clusterodm:
    image: opendronemap/clusterodm
    container_name: clusterodm
    ports:
      - "4000:3000"
      - "8080:8080"
      - "10000:10000"
    volumes:
      - ./docker/data:/var/www/data
    restart: on-failure:10
    depends_on:
      - nodeodm
